### ISSUE TITLE
FB login Page(Backend Part)

### ISSUE THREAD

**Issue by nkmishra1997** [nkmishra1997/bnb2018#1]
using passport.js create the fb login.

**Comment by nkmishra1997** [comment]
@vegeta1509  you can start working now

**Comment by nkmishra1997** [comment]
@vegeta1509  you have created a new app AuthFb. Don't do this. You created express app(AuthFb) inside express app(bnb2018) which is not what we want. Close your PR, fork again and this time you have to make fb loign for this app itself.

**Comment by vegeta1509** [comment]
sir matlb mujhe login wala page bdlna h or fir page ko bnb k home page par redirect karna h
