### ISSUE TITLE
Company Schema

### ISSUE THREAD

**Issue by nkmishra1997** [nkmishra1997/bnb2018#3]
@VibhorCodecianGupta
@manmeet-123

**Comment by vibhorgupta-gh** [comment]
The routes /newsdetail and /companydetail fetch the respective details of a particular company right? so the company name will also be queried in a query string after the route, right?

**Comment by nkmishra1997** [comment]
Required Schema:  
name  
symbol  
description  
stockPrice  
availableQuantity  
totalQuantity  
annualGrowthRate  
history : timeStamp , stockPrice , availableQuantity  
complementaryCompany : company , factor   
supplementaryCompany :  company , factor

**Comment by nkmishra1997** [comment]
@ishikahooda validators
