### ISSUE TITLE
Customer Schema

### ISSUE THREAD

**Issue by nkmishra1997** [nkmishra1997/bnb2018#4]
@vegeta1509 @Ishikahooda

**Comment by vibhorgupta-gh** [comment]
What's going to be the layout of the customer? What information is this model expected to store?

**Comment by Ishikahooda** [comment]
Atleast show the the last year website so that we can figure out what all is to be done?
I haven't even opened the website of bnb'16-17 at that time.

**Comment by vegeta1509** [comment]
i think in customer’s schema there will be name/value pair for user id, types of stock, no. of stock, money, shorted stocks etc…

**Comment by nkmishra1997** [comment]
Required Schema:   
ban  (to ban people we dont like :smiley: )   
Facebook data: Name, id, email etc   
accountBalance   
activity : company , timeStamp , action (Buy,Sell etc), quantity, price    
stockHoldings :  company, quantity  
stockShorted:  company, quantity  
loan : taken , amount , takeOutTime , repayTime .

**Comment by vibhorgupta-gh** [comment]
timeStamp, takeOutTime, repayTime mein Date() object se kaam chal jaega sir, ya should i use npm mongoose-timestamp?

**Comment by nkmishra1997** [comment]
@VibhorCodecianGupta  It will better to avoid using packages for small things like this. Simply doing Date.now() can do it I guess. Look for package which can convert mongoose dates to normal javaScript date. See more about Difference between the two
